{% set name = "msal" %}
{% set version = "1.32.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a36837fa9ead0b63f3d7aed51f9af5d586e482fbec196bbb8e5dc9492ee0f1a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests <3,>=2.0.0
    - pyjwt <3,>=1.0.0
    - cryptography <47,>=2.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - msal
    - msal.oauth2cli

about:
  home: https://github.com/AzureAD/microsoft-authentication-library-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Authentication Library (MSAL) for Python makes it easy to authenticate to Azure Active Directory

  description: |
    The MSAL library for Python enables your app to access the Microsoft Cloud by supporting
    authentication of users with Microsoft Azure Active Directory accounts and Microsoft Accounts
    using industry standard OAuth2 and OpenID Connect.
  doc_url: https://msal-python.readthedocs.io
  dev_url: https://github.com/AzureAD/microsoft-authentication-library-for-python

extra:
  recipe-maintainers:
    - roederja
    - dhirschfeld
